added command for cleaning up branch
cleanup = archive as tag + delete

diff --git a/sing b/sing
--- a/sing
+++ b/sing
@@ -4,11 +4,11 @@
 info() {
     echo "$@";
 }
-die() { 
+die() {
     echo "$@" >&2;
     exit 1
 }
-escape() { 
+escape() {
     echo "$1" | sed 's/\([\.\$\*]\)/\\\1/g'
 }
 has() {
@@ -18,11 +18,11 @@ has() {
 }
 
 # git queries
-local_branches() { 
+local_branches() {
     git branch --no-color | sed 's/^[* ] //'
 }
 current_branch() {
-	git branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g'
+    git branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g'
 }
 
 # git commands
@@ -51,12 +51,12 @@ delete() {
 
 branch() {
     NEW="$1"
-    
+
     # git will fail fast if NEW already exists
     if test "$NEW" = "$(current_branch)" || has $NEW $(local_branches); then
-	info "$NEW already exits, not branching"
+        info "$NEW already exits, not branching"
     else
-	git branch "$@" || die
+        git branch "$@" || die
     fi
 }
 
@@ -75,18 +75,18 @@ cmd_update() {
     # save the initial branch to switch back to it after updating MASTER
     INITIAL="$(current_branch)"
 
-    # 'pull' changes from SVN into MASTER    
-    checkout "$MASTER"	    
+    # 'pull' changes from SVN into MASTER
+    checkout "$MASTER"
     svn_rebase
 
     # then get them into the initial branch too if it wasnt MASTER
     if test "$INITIAL" != "$MASTER"; then
-	# simply merging MASTER into INITIAL should cause headaches with 
-	# non-linear history once INITIAL is finished and dcommitted back to SVN,
-	# so better consistently rebase everything. 
-	# by that some of the benefits of using git are lost but
-	# having cheap and local branches is still preferable.
-	rebase "$MASTER" "$INITIAL"
+        # simply merging MASTER into INITIAL should cause headaches with
+        # non-linear history once INITIAL is finished and dcommitted back to SVN,
+        # so better consistently rebase everything.
+        # by that some of the benefits of using git are lost but
+        # having cheap and local branches is still preferable.
+        rebase "$MASTER" "$INITIAL"
     fi
 }
 
@@ -94,7 +94,7 @@ cmd_start() {
     # dont know what to start without a branchname
     require_args "$@"
     NEW="$1"
-    
+
     # starting point is always MASTER
     checkout $MASTER
 
@@ -105,10 +105,10 @@ cmd_start() {
 }
 cmd_finish() {
     if test $# -eq 0; then
-	COMPLETE="$(current_branch)"
+        COMPLETE="$(current_branch)"
     else
-	COMPLETE="$1"
-	checkout $COMPLETE
+        COMPLETE="$1"
+        checkout $COMPLETE
     fi
 
     # after this step MASTER (and therefore its corresponding SVN branch)
@@ -116,29 +116,46 @@ cmd_finish() {
     cmd_update
 
     if test "$COMPLETE" = "$MASTER"; then
-	# how to interpret 'finish MASTER'? it should not be deleted
-	# so just dcommit and do nothing else
-	svn_dcommit
+        # how to interpret 'finish MASTER'? it should not be deleted
+        # so just dcommit and do nothing else
+        svn_dcommit
     else
-	checkout $MASTER
+        checkout $MASTER
 
-	# this is guaranteed to be a fast-forward merge: 
-	# COMPLETE was just rebased onto MASTER
-	merge $COMPLETE
-    
-	# 'push' to upstream
-	svn_dcommit
-    
-	# clean up and it's done
-	archive $COMPLETE
-	delete $COMPLETE
+        # this is guaranteed to be a fast-forward merge:
+        # COMPLETE was just rebased onto MASTER
+        merge $COMPLETE
+
+        # 'push' to upstream
+        svn_dcommit
+
+        # clean up and it's done
+        cmd_cleanup $COMPLETE
     fi
+}
+
+cmd_cleanup() {
+    if test $# -eq 0; then
+        COMPLETE="$(current_branch)"
+        # cant delete the branch youre currently on
+        checkout $MASTER
+    else
+        COMPLETE="$1"
+        checkout $COMPLETE
+    fi
+
+    if test $COMPLETE -eq $MASTER; then
+        die "cannot cleanup $MASTER: it's the master branch"
+    fi
+
+    archive $COMPLETE
+    delete $COMPLETE
 }
 
 require_args() {
     if test $# -eq 0; then
-	usage
-	die
+        usage
+        die
     fi
 }
 
@@ -154,17 +171,17 @@ main() {
     require_args "$@"
     # must be in a git repo
     if ! git rev-parse --git-dir >/dev/null 2>&1; then
-	die "error: Not a git repository"
+        die "error: Not a git repository"
     fi
 
-    # save first subcommand and remove it from the given arguments 
+    # save first subcommand and remove it from the given arguments
     SUBCOMMAND="$1"
     shift
 
-    # no need to go any further if user only wants info on usage    
+    # no need to go any further if user only wants info on usage
     if test "$SUBCOMMAND" = "usage" || test "$SUBCOMMAND" = "help"; then
-	usage
-	exit 0
+        usage
+        exit 0
     fi
 
     # this is what the branch is called that all the git-svn-specific commands are executed on
@@ -172,28 +189,28 @@ main() {
 
     # check if this is a sing-enabled repo
     if ! has $MASTER $(local_branches); then
-	die "error: branch $MASTER not found"
+        die "error: branch $MASTER not found"
     fi
 
     # dont want to lose anything, so better abort straight away
     # there might be better solutions: prompt to stash?
     if ! git diff --no-ext-diff --ignore-submodules --quiet --exit-code; then
-	die "error: working tree contains unstaged changes, aborting"
+        die "error: working tree contains unstaged changes, aborting"
     fi
     if ! git diff-index HEAD --ignore-submodules --quiet --exit-code; then
-	die "error: index contains uncommited changes, aborting"
-    fi
-    
-    # delegate to subcommands
-    cmd_$SUBCOMMAND "$@"
-    
-    # 127 exit code for unknown subcommand on my system (ubuntu 14.04)
-    if test $? -eq 127; then
-	usage
-	die
+        die "error: index contains uncommited changes, aborting"
     fi
 
-    # if it gets here there should have been no errors: 
+    # delegate to subcommands
+    cmd_$SUBCOMMAND "$@"
+
+    # 127 exit code for unknown subcommand on my system (ubuntu 14.04)
+    if test $? -eq 127; then
+        usage
+        die
+    fi
+
+    # if it gets here there should have been no errors:
     # all the subcommands are supposed to die (exit 1) if git returns an exit code != 0
     exit 0
 }
