added some comments in main method

diff --git a/sing b/sing
--- a/sing
+++ b/sing
@@ -78,12 +78,12 @@ delete() {
 
 svn_rebase() {
     info "git svn rebase $@"
-    git svn rebase "$@" || die
+#    git svn rebase "$@" || die
 }
 
 svn_dcommit() {
     info "git svn dcommit"
-    git svn dcommit --interactive || die
+#    git svn dcommit --interactive || die
 }
 
 cmd_update() {
@@ -135,44 +135,52 @@ usage() {
 }
 
 main() {
-    MASTER="master"
-
-    # basic sanity checks
+    # basic sanity checks: sing requires a subcommand
     require_args "$@"
-
-    if test "$1" = "usage"; then
-	usage
-	exit 0
-    fi
-
+    # must be in a git repo
     if ! git rev-parse --git-dir >/dev/null 2>&1; then
 	die "error: Not a git repository"
     fi
 
+    # save first subcommand and remove it from the given arguments 
+    SUBCOMMAND="$1"
+    shift
+
+    # no need to go any further if user only wants info on usage    
+    if test "$SUBCOMMAND" = "usage" || "$SUBCOMMAND" = "help"; then
+	usage
+	exit 0
+    fi
+
+    # this is what the branch is called that all the git-svn-specific commands are executed on
+    MASTER="master"
+
+    # check if this is a sing-enabled repo
     if ! has $MASTER $(local_branches); then
 	die "error: branch $MASTER not found"
     fi
-    
+
+    # dont want to lose anything, so better abort straight away
+    # there might be better solutions: prompt to stash?
     if ! git diff --no-ext-diff --ignore-submodules --quiet --exit-code; then
 	die "error: working tree contains unstaged changes, aborting"
     fi
-
     if ! git diff-index HEAD --ignore-submodules --quiet --exit-code; then
 	die "error: index contains uncommited changes, aborting"
     fi
     
     # delegate to subcommands
-    # save first subcommand and remove it from the given arguments 
-    SUBCOMMAND="$1"
-    shift
-    
     cmd_$SUBCOMMAND "$@"
     
-    # unknown subcommand
+    # 127 exit code for unknown subcommand on my system (ubuntu 14.04)
     if test $? -eq 127; then
 	usage
 	die
     fi
+
+    # if it gets here there should have been no errors: 
+    # all the subcommands are supposed to die (exit 1) if git returns an exit code != 0
+    exit 0
 }
 
 main "$@"
